import{a as v,S as E,i as a}from"./assets/vendor-Dy2ZTtfi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const b="50868360-a376148e060c1128e2434e35d",P="https://pixabay.com/api/",q=15;async function p(r,e){const s={key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:e};return(await v.get(P,{params:s})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),x=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const e=r.map(s=>`
    <li class="gallery-item">
      <a href="${s.largeImageURL}">
        <img src="${s.webformatURL}" alt="${s.tags}" width="360"/>
      </a>
      <div class="info">
        <p class="text-descr">Likes: <span class="descr">${s.likes}</span></p>
        <p class="text-descr">Views: <span class="descr">${s.views}</span></p>
        <p class="text-descr">Comments: <span class="descr">${s.comments}</span></p>
        <p class="text-descr">Downloads: <span class="descr">${s.downloads}</span></p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",e),x.refresh()}function B(){m.innerHTML=""}function L(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}function S(){y.classList.remove("hidden")}function u(){y.classList.add("hidden")}const $=document.querySelector(".form"),M=document.querySelector(".load-more");let i="",c=1,f=0,n=0;$.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.currentTarget.elements["search-text"].value.trim(),c=1,n=0,!i){a.warning({title:"Warning",message:"Please enter a search term!"});return}B(),u(),L();try{const e=await p(i,c);f=e.totalHits,n=e.hits.length,e.hits.length===0?(a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}),u()):(g(e.hits),n<f&&S())}catch(e){a.error({title:"Error",message:"Something went wrong. Please try again."}),console.error(e)}finally{w()}});M.addEventListener("click",async()=>{c+=1,L(),u();try{const r=await p(i,c);g(r.hits),n+=r.hits.length,n>=f?a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}):S();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch(r){a.error({title:"Error",message:"Something went wrong. Please try again."}),console.error(r)}finally{w()}});
//# sourceMappingURL=index.js.map
